# Дополнительный файл к заданию "Свойства и типы нечетких бинарных отношений"

In [2]:
import numpy as np
import os

In [3]:
def read_tex(text:str) -> np.ndarray:
    """
    Read .tex string line containing array information(still needs manual input)
    """
    lines = text.replace(' ', "").split('\\')
    elements = [l.lstrip("&").split('&') for l in lines]
    arr = np.array([list(map(lambda x: float(x), line)) for line in elements])
    return arr

In [4]:
def mu(ix: np.int, iy: np.int, arr1: np.ndarray, arr2=np.nan) -> np.float:
    """
    Returns (max-min)-composition for single pair
    """
    if arr2 is np.nan:
        arr2 = arr
    xz = arr1[ix,:]
    zy = arr2[:,iy]
    choose = np.array(list(map(lambda x: min(x), list(zip(xz,zy)))))
    val = max(choose)
    return val

In [5]:
def calc(arr1:np.ndarray, arr2=np.nan) -> np.ndarray:
    """
    Returns (max-min)-composition for given arrays
    """
    if arr2 is np.nan:
        arr2 = arr1
    x = arr1.shape[0]
    y = arr2.shape[1]
    pot = np.empty((x,y))
    for ix in range(0,x):
        for iy in range(0, y):
            pot[ix,iy] = mu(ix,iy,arr1,arr2)
    return pot

In [6]:
def transitive(arr:np.ndarray, arr_squared:np.ndarray) -> bool:
    """
    Returns True if arr_squared \subset arr <=> arr is fuzzy transitive
    """
    return (arr_squared <= arr).all()

In [7]:
def save_tex(arr:np.ndarray, name:str):
    """This done in order to put matrix in .tex file"""
    os.makedirs("outputs/relations/", exist_ok=True)
    np.savetxt("outputs/relations/{}.csv".format(name), arr, delimiter=' & ', fmt='%1.1f', newline=' \\\\\n')

## Задание 1

In [8]:
R_1 = "& 0 & 1 & 1   & 1   & 1   \ & 0 & 0 & 0.9 & 0.7 & 0.3 \ & 0 & 0 & 0   & 0.7 & 0.3 \& 0 & 0 & 0   & 0   & 0.3 \& 0 & 0 & 0   & 0   & 0   "
R_2 = "0   & 0.3 & 1   & 0   & 0.5 \& 0.3 & 0.2 & 0   & 0.8 & 0.1 \& 1   & 0   & 0   & 0.2 & 1   \ & 0   & 0.8 & 0.2 & 1   & 0.4 \& 0.5 & 0.1 & 1   & 0.4 & 0.4"
R_3 = "1 & 0.5 & 0.5 & 0 & 0.7 \& 0 & 1   & 0.7 & 0 & 0   \& 0 & 1   & 1   & 0 & 0   \& 0 & 0.3 & 0.3 & 1 & 0   \& 1 & 0.5 & 0.5 & 0 & 1 "
R_4 = "0   & 0 & 0.3 & 0.2 & 0   \& 0.6 & 1 & 0.8 & 1   & 0.2 \& 0.2 & 0 & 1   & 0.8 & 0.3 \& 0   & 0 & 0   & 1   & 0   \& 1   & 0 & 0.2 & 0.6 & 0 "
R = (R_1, R_2, R_3, R_4)

In [9]:
for r in R:
    arr = read_tex(r)
    arr_squared = calc(arr)
    transit = transitive(arr, arr_squared)
    print('This is a given array:\n{}\nThis is the array squared:\n{}\nGiven relation is {}'.format(arr, arr_squared, "transitive" if transit else "non-transitive"))
    

This is a given array:
[[0.  1.  1.  1.  1. ]
 [0.  0.  0.9 0.7 0.3]
 [0.  0.  0.  0.7 0.3]
 [0.  0.  0.  0.  0.3]
 [0.  0.  0.  0.  0. ]]
This is the array squared:
[[0.  0.  0.9 0.7 0.3]
 [0.  0.  0.  0.7 0.3]
 [0.  0.  0.  0.  0.3]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]
Given relation is transitive
This is a given array:
[[0.  0.3 1.  0.  0.5]
 [0.3 0.2 0.  0.8 0.1]
 [1.  0.  0.  0.2 1. ]
 [0.  0.8 0.2 1.  0.4]
 [0.5 0.1 1.  0.4 0.4]]
This is the array squared:
[[1.  0.2 0.5 0.4 1. ]
 [0.2 0.8 0.3 0.8 0.4]
 [0.5 0.3 1.  0.4 0.5]
 [0.4 0.8 0.4 1.  0.4]
 [1.  0.4 0.5 0.4 1. ]]
Given relation is non-transitive
This is a given array:
[[1.  0.5 0.5 0.  0.7]
 [0.  1.  0.7 0.  0. ]
 [0.  1.  1.  0.  0. ]
 [0.  0.3 0.3 1.  0. ]
 [1.  0.5 0.5 0.  1. ]]
This is the array squared:
[[1.  0.5 0.5 0.  0.7]
 [0.  1.  0.7 0.  0. ]
 [0.  1.  1.  0.  0. ]
 [0.  0.3 0.3 1.  0. ]
 [1.  0.5 0.5 0.  1. ]]
Given relation is transitive
This is a given array:
[[0.  0.  0.3 0.2 0. ]
 [0.6 1.  0.8 1. 

## Задание 2

In [10]:
def union(arr1:np.ndarray, arr2:np.ndarray) -> np.ndarray:
    """
    Computes union of 2 fuzzy relations
    """
    shape = arr1.shape
    pot = np.empty(shape)
    for ix in range(0,shape[0]):
        for iy in range(0,shape[1]):
            pot[ix,iy] = max(arr1[ix,iy],arr2[ix,iy])
    return pot

In [11]:
def trans_closure(arr:np.ndarray) -> np.ndarray:
    """
    Computes transitive closure of a fuzzy relation
    """
    pot = arr
    new_arr = calc(arr)
    count = 1
    print(count)
    print(new_arr)
    print('----------')
    if (new_arr==arr).all():
        return pot
    else:
        pot = union(new_arr,arr)
        while True:
            prev_arr = new_arr
            new_arr = calc(new_arr,arr)
            count += 1
            print(count)
            print(new_arr)
            print('----------')
            if (prev_arr==new_arr).all():
                return pot
            else:
                pot = union(new_arr,arr)

In [21]:
R1 = read_tex(R_1)
print("R1:\n{}".format(R1))
trans_closure(R1)

R1:
[[0.  1.  1.  1.  1. ]
 [0.  0.  0.9 0.7 0.3]
 [0.  0.  0.  0.7 0.3]
 [0.  0.  0.  0.  0.3]
 [0.  0.  0.  0.  0. ]]
1
[[0.  0.  0.9 0.7 0.3]
 [0.  0.  0.  0.7 0.3]
 [0.  0.  0.  0.  0.3]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]
----------
2
[[0.  0.  0.  0.7 0.3]
 [0.  0.  0.  0.  0.3]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]
----------
3
[[0.  0.  0.  0.  0.3]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]
----------
4
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------
5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------


array([[0. , 1. , 1. , 1. , 1. ],
       [0. , 0. , 0.9, 0.7, 0.3],
       [0. , 0. , 0. , 0.7, 0.3],
       [0. , 0. , 0. , 0. , 0.3],
       [0. , 0. , 0. , 0. , 0. ]])

In [13]:
R2 = read_tex(R_2)
trans_closure(R2)

1
[[1.  0.2 0.5 0.4 1. ]
 [0.2 0.8 0.3 0.8 0.4]
 [0.5 0.3 1.  0.4 0.5]
 [0.4 0.8 0.4 1.  0.4]
 [1.  0.4 0.5 0.4 1. ]]
----------
2
[[0.5 0.4 1.  0.4 0.5]
 [0.4 0.8 0.4 0.8 0.4]
 [1.  0.4 0.5 0.4 1. ]
 [0.4 0.8 0.4 1.  0.4]
 [0.5 0.4 1.  0.4 0.5]]
----------
3
[[1.  0.4 0.5 0.4 1. ]
 [0.4 0.8 0.4 0.8 0.4]
 [0.5 0.4 1.  0.4 0.5]
 [0.4 0.8 0.4 1.  0.4]
 [1.  0.4 0.5 0.4 1. ]]
----------
4
[[0.5 0.4 1.  0.4 0.5]
 [0.4 0.8 0.4 0.8 0.4]
 [1.  0.4 0.5 0.4 1. ]
 [0.4 0.8 0.4 1.  0.4]
 [0.5 0.4 1.  0.4 0.5]]
----------
5
[[1.  0.4 0.5 0.4 1. ]
 [0.4 0.8 0.4 0.8 0.4]
 [0.5 0.4 1.  0.4 0.5]
 [0.4 0.8 0.4 1.  0.4]
 [1.  0.4 0.5 0.4 1. ]]
----------
6
[[0.5 0.4 1.  0.4 0.5]
 [0.4 0.8 0.4 0.8 0.4]
 [1.  0.4 0.5 0.4 1. ]
 [0.4 0.8 0.4 1.  0.4]
 [0.5 0.4 1.  0.4 0.5]]
----------
7
[[1.  0.4 0.5 0.4 1. ]
 [0.4 0.8 0.4 0.8 0.4]
 [0.5 0.4 1.  0.4 0.5]
 [0.4 0.8 0.4 1.  0.4]
 [1.  0.4 0.5 0.4 1. ]]
----------
8
[[0.5 0.4 1.  0.4 0.5]
 [0.4 0.8 0.4 0.8 0.4]
 [1.  0.4 0.5 0.4 1. ]
 [0.4 0.8 0.4 1.  0.4]
 [0

KeyboardInterrupt: 

In [14]:
calc(R2)

array([[1. , 0.2, 0.5, 0.4, 1. ],
       [0.2, 0.8, 0.3, 0.8, 0.4],
       [0.5, 0.3, 1. , 0.4, 0.5],
       [0.4, 0.8, 0.4, 1. , 0.4],
       [1. , 0.4, 0.5, 0.4, 1. ]])

In [15]:
R3 = read_tex(R_3)
trans_closure(R3)

1
[[1.  0.5 0.5 0.  0.7]
 [0.  1.  0.7 0.  0. ]
 [0.  1.  1.  0.  0. ]
 [0.  0.3 0.3 1.  0. ]
 [1.  0.5 0.5 0.  1. ]]
----------


array([[1. , 0.5, 0.5, 0. , 0.7],
       [0. , 1. , 0.7, 0. , 0. ],
       [0. , 1. , 1. , 0. , 0. ],
       [0. , 0.3, 0.3, 1. , 0. ],
       [1. , 0.5, 0.5, 0. , 1. ]])

In [16]:
R4 = read_tex(R_4)
R4_close = trans_closure(R4)
save_tex(R4_close, 'task2_R4')

1
[[0.2 0.  0.3 0.3 0.3]
 [0.6 1.  0.8 1.  0.3]
 [0.3 0.  1.  0.8 0.3]
 [0.  0.  0.  1.  0. ]
 [0.2 0.  0.3 0.6 0.2]]
----------
2
[[0.3 0.  0.3 0.3 0.3]
 [0.6 1.  0.8 1.  0.3]
 [0.3 0.  1.  0.8 0.3]
 [0.  0.  0.  1.  0. ]
 [0.2 0.  0.3 0.6 0.3]]
----------
3
[[0.3 0.  0.3 0.3 0.3]
 [0.6 1.  0.8 1.  0.3]
 [0.3 0.  1.  0.8 0.3]
 [0.  0.  0.  1.  0. ]
 [0.3 0.  0.3 0.6 0.3]]
----------
4
[[0.3 0.  0.3 0.3 0.3]
 [0.6 1.  0.8 1.  0.3]
 [0.3 0.  1.  0.8 0.3]
 [0.  0.  0.  1.  0. ]
 [0.3 0.  0.3 0.6 0.3]]
----------


## Задание 3

In [17]:
R = "1 & 0.7 & 0.2 & 0 & 0.8 & 1   \& 0 & 1   & 0.2 & 0 & 0   & 0   \& 0 & 0.5 & 1   & 0 & 0   & 0   \& 0 & 0.1 & 0.1 & 1 & 0.1 & 0.1 \& 0 & 0   & 0   & 0 & 1   & 0.8 \& 0 & 0   & 0   & 0 & 0.8 & 1"
arr = read_tex(R)

In [18]:
arr2 = calc(arr)
istrans = transitive(arr,arr2)
save_tex(arr2, 'task3')
print('Relation is transitive') if istrans else print('Relation is not transitive')

Relation is transitive


## Задание 4

In [19]:
R = "1   & 0.1 & 0.1 & 0   & 0   & 0.5 \& 0.1 & 1   & 0.6 & 0   & 0   & 0.1 \& 0.1 & 0.6 & 1   & 0   & 0   & 0.1 \& 0   & 0   & 0   & 1  \
    & 0.3 & 0   \& 0   & 0   & 0   & 0.3 & 1   & 0   \& 0.5 & 0.1 & 0.1 & 0   & 0   & 1"
arr = read_tex(R)

In [20]:
arr2 = calc(arr)
istrans = transitive(arr,arr2)
save_tex(arr2, 'task4')
print('Relation is transitive') if istrans else print('Relation is not transitive')

Relation is transitive
